### ISSUE TITLE
This needs sparkiness

### ISSUE THREAD

**Issue by faddat** [ausbitbank/steemvids#1]
Can we help bring you sparkiness?  

I want to.

**Comment by ausbitbank** [comment]
Can you be more specific (via chat message) .. It's alpha, I'm open to suggestions but like I said in my reply on steemit I'm not looking to handle video hosting directly right now..

**Comment by faddat** [comment]
Yes I surely can.  Please get ahold of me on google hangouts-- faddat@gmail.com

I'm building an API for steem that you need.
